# Generated by Django 5.1.4 on 2025-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutuspagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspagecontent',
            name='img_link',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
    ]
