# Generated by Django 5.1.4 on 2025-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_aboutuspagecontent_img_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPageContentWithImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us Page', max_length=255)),
                ('sub_title', models.CharField(default='About Delta LP Gas Ltd.', max_length=255)),
                ('content', models.TextField()),
                ('img_link', models.ImageField(blank=True, null=True, upload_to='about_us/')),
            ],
        ),
    ]
