# Generated by Django 5.1.4 on 2025-06-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutuspagecontentwithimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_time', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('call_any_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Header Info',
                'verbose_name_plural': 'Header Info',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us 1st', 'verbose_name_plural': 'About Us 1st'},
        ),
        migrations.AlterModelOptions(
            name='aboutuspagecontentwithimg',
            options={'verbose_name': 'ABOUT US 002', 'verbose_name_plural': 'ABOUT US 002'},
        ),
    ]
