# Generated by Django 5.1.4 on 2025-06-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_headerinfo_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBelowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_01', models.CharField(max_length=255)),
                ('description_01', models.TextField()),
                ('text_02', models.CharField(max_length=255)),
                ('description_02', models.TextField()),
                ('text_03', models.CharField(max_length=255)),
                ('description_03', models.TextField()),
            ],
            options={
                'verbose_name': 'Slider Below Section',
                'verbose_name_plural': 'Slider Below Section',
            },
        ),
    ]
