# Generated by Django 5.1.4 on 2025-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_01', models.CharField(max_length=255)),
                ('description_01', models.TextField()),
                ('title_02', models.CharField(max_length=255)),
                ('description_02', models.TextField()),
                ('left_image', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Home About Us',
                'verbose_name_plural': 'Home About Us',
            },
        ),
    ]
