# Generated by Django 5.1.4 on 2025-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_homeaboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutus',
            name='left_image',
            field=models.ImageField(upload_to='home_about_us/'),
        ),
    ]
