# Generated by Django 5.1.4 on 2025-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_homeaboutus_left_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('product_1_name', models.CharField(max_length=255)),
                ('product_1_image', models.ImageField(upload_to='product_images/')),
                ('product_2_name', models.CharField(max_length=255)),
                ('product_2_image', models.ImageField(upload_to='product_images/')),
                ('product_3_name', models.CharField(max_length=255)),
                ('product_3_image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'HOME PRODUCTS',
                'verbose_name_plural': 'HOME PRODUCTS',
            },
        ),
        migrations.AlterModelOptions(
            name='headerinfo',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
    ]
