# Generated by Django 5.1.4 on 2025-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_homeproducts_alter_headerinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePromotionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Promotional Video',
                'verbose_name_plural': 'Promotional Video',
            },
        ),
        migrations.AlterModelOptions(
            name='homeproducts',
            options={'verbose_name': 'Home Products', 'verbose_name_plural': 'Home Products'},
        ),
    ]
