# Generated by Django 5.1.4 on 2025-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_homepromotionalvideo_alter_homeproducts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('left_image', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
        migrations.AlterModelOptions(
            name='homepromotionalvideo',
            options={'verbose_name': 'Home Promotional Video', 'verbose_name_plural': 'Home Promotional Video'},
        ),
    ]
