# Generated by Django 5.1.4 on 2025-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aboutuspage_alter_homepromotionalvideo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVisionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('title2', models.CharField(max_length=255)),
                ('description2', models.TextField()),
                ('left_image', models.ImageField(upload_to='mission_vision/')),
            ],
            options={
                'verbose_name': 'Mission Vision Page',
                'verbose_name_plural': 'Mission Vision Page',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us 1st Test', 'verbose_name_plural': 'About Us 1st Test'},
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='left_image',
            field=models.ImageField(upload_to='about_us/'),
        ),
    ]
