# Generated by Django 5.1.4 on 2025-06-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_missionvisionpage_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_img', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Products Add',
                'verbose_name_plural': 'Product Add',
            },
        ),
    ]
