# Generated by Django 5.1.4 on 2025-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productsadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAddList',
            fields=[
            ],
            options={
                'verbose_name': 'Products List',
                'verbose_name_plural': 'Products List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.productsadd',),
        ),
        migrations.AddField(
            model_name='productsadd',
            name='product_status',
            field=models.CharField(default='false', max_length=255),
        ),
    ]
