# Generated by Django 5.1.4 on 2025-06-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_productsaddlist_productsadd_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_1', models.CharField(max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('map_link', models.TextField(help_text='Paste your <iframe> embed code here')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.AlterField(
            model_name='productsadd',
            name='product_img',
            field=models.ImageField(blank=True, default='delta_header_logo.png', upload_to=''),
        ),
    ]
