# Generated by Django 5.1.4 on 2025-06-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contactpage_alter_productsadd_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=255)),
                ('headline_one', models.CharField(max_length=255)),
                ('description_one', models.TextField()),
                ('feature_image_one', models.ImageField(blank=True, null=True, upload_to='media/distribution/')),
                ('title_two', models.CharField(max_length=255)),
                ('headline_two', models.CharField(max_length=255)),
                ('description_two', models.TextField()),
                ('headline_three', models.CharField(max_length=255)),
                ('description_three', models.TextField()),
                ('headline_four', models.CharField(max_length=255)),
                ('description_four', models.TextField()),
                ('headline_five', models.CharField(max_length=255)),
                ('description_five', models.TextField()),
                ('feature_image_two', models.ImageField(blank=True, null=True, upload_to='media/distribution/')),
            ],
            options={
                'verbose_name': 'Distribution Page',
                'verbose_name_plural': 'Distribution Page',
            },
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email_1',
            field=models.CharField(max_length=100, verbose_name='Email 01'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 02'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_link',
            field=models.TextField(verbose_name='Map Link'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_number_1',
            field=models.CharField(max_length=20, verbose_name='Phone Number 01'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number 02'),
        ),
    ]
