# Generated by Django 5.1.4 on 2025-06-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_distributionpage_alter_contactpage_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionpage',
            name='description_six',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionpage',
            name='headline_six',
            field=models.CharField(default='Not provided', max_length=255),
            preserve_default=False,
        ),
    ]
