# Generated by Django 5.1.4 on 2025-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_distributionpage_description_six_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('feature_image', models.ImageField(upload_to='cylinder/')),
            ],
            options={
                'verbose_name': 'Cylinder Page',
                'verbose_name_plural': 'Cylinder Page',
            },
        ),
    ]
