# Generated by Django 5.1.4 on 2025-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cylinderpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinderpage',
            old_name='description',
            new_name='cylinder_1_description',
        ),
        migrations.RenameField(
            model_name='cylinderpage',
            old_name='cylinder_name',
            new_name='cylinder_1_name',
        ),
        migrations.RemoveField(
            model_name='cylinderpage',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_1_image',
            field=models.ImageField(default='Default Text', upload_to='media/cylinder/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_2_description',
            field=models.TextField(default='Default Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_2_image',
            field=models.ImageField(default='Not provided', upload_to='media/cylinder/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_2_name',
            field=models.CharField(default='Not provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_3_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_3_image',
            field=models.ImageField(default='Not provided', upload_to='media/cylinder/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderpage',
            name='cylinder_3_name',
            field=models.CharField(default='Not provided', max_length=255),
            preserve_default=False,
        ),
    ]
