# Generated by Django 5.1.4 on 2025-06-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_description_cylinderpage_cylinder_1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_headline', models.CharField(max_length=255)),
                ('page_feature_image', models.ImageField(upload_to='media/bulk_page_images/')),
                ('description', models.TextField()),
                ('title_01', models.CharField(max_length=255)),
                ('description_01', models.TextField()),
                ('title_02', models.CharField(max_length=255)),
                ('description_02', models.TextField()),
                ('title_03', models.CharField(max_length=255)),
                ('description_03', models.TextField()),
            ],
            options={
                'verbose_name': 'Bulk Page',
                'verbose_name_plural': 'Bulk Page',
            },
        ),
    ]
