# Generated by Django 5.1.4 on 2025-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='board_of_directors/')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_img',
            field=models.ImageField(upload_to='media/sliders/'),
        ),
    ]
