# Generated by Django 5.1.4 on 2025-06-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_boardofdirector_alter_slider_slider_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReticulationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_headline_01', models.CharField(max_length=255)),
                ('description_01', models.TextField()),
                ('advantage_list', models.TextField()),
                ('left_image', models.ImageField(upload_to='reticulation_images/')),
                ('section_headline_02', models.CharField(max_length=255)),
                ('title_02', models.CharField(max_length=255)),
                ('description_02', models.TextField()),
                ('title_03', models.CharField(max_length=255)),
                ('description_03', models.TextField()),
                ('right_image', models.ImageField(upload_to='reticulation_images/')),
            ],
            options={
                'verbose_name': 'Reticulation Page',
                'verbose_name_plural': 'Reticulation Page',
            },
        ),
    ]
