# Generated by Django 5.1.4 on 2025-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_faqadd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqadd',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
