# Generated by Django 5.1.4 on 2025-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_faqadd_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
