# Generated by Django 5.1.4 on 2025-07-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_headerinfo_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='header_logos/'),
        ),
    ]
