# Generated by Django 5.1.4 on 2025-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_headerinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_credits_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
