# Generated by Django 5.1.4 on 2025-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_footer_footer_credits_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
