# Generated by Django 5.1.4 on 2025-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_footer_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
