# Generated by Django 5.1.4 on 2025-07-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_footer_youtube_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardofdirector',
            old_name='image',
            new_name='director_image',
        ),
    ]
