# Generated by Django 5.1.4 on 2025-07-23 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_image_boardofdirector_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardofdirector',
            name='about_of_director',
            field=models.TextField(default=datetime.datetime(2025, 7, 23, 4, 34, 14, 864225, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardofdirector',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='boardofdirector',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='boardofdirector',
            name='joining_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardofdirector',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='boardofdirector',
            name='qualification',
            field=models.CharField(default=datetime.datetime(2025, 7, 23, 4, 34, 55, 735286, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
