# Generated by Django 5.1.4 on 2025-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_boardofdirector_about_of_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspagecontent',
            name='distribution_network_img',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
    ]
