# Generated by Django 5.1.4 on 2025-07-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_aboutuspagecontent_distribution_network_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuspagecontent',
            old_name='distribution_network_img',
            new_name='distribution_map_img',
        ),
    ]
