# Generated by Django 5.1.4 on 2025-07-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_distribution_network_img_aboutuspagecontent_distribution_map_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuspagecontent',
            old_name='distribution_map_img',
            new_name='dist_map_link',
        ),
    ]
