# Generated by Django 5.1.4 on 2025-07-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_distribution_map_img_aboutuspagecontent_dist_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email_1',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone_number_1',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone_number_2',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_1_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_1_email',
            field=models.EmailField(default='not-provided@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_1_map',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_1_name',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_1_phone_1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_1_phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_2_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_2_email',
            field=models.EmailField(default='not-provided@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_2_map',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_2_name',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_2_phone_1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_2_phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_3_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_3_email',
            field=models.EmailField(default='not-provided@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_3_map',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_3_name',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_3_phone_1',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_3_phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
