# Generated by Django 5.1.4 on 2025-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_contactpage_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
