# Generated by Django 5.1.4 on 2025-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_slider_options_slider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsadd',
            name='product_status',
            field=models.BooleanField(default=False),
        ),
    ]
