# Generated by Django 5.1.4 on 2025-08-13 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_cylinderlpgasproductsadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderlpgasproductsadd',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cylinder_lpg_products/'),
        ),
        migrations.AddField(
            model_name='cylinderlpgasproductsadd',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='cylinder_lpg_products/'),
        ),
        migrations.AddField(
            model_name='cylinderlpgasproductsadd',
            name='product_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='cylinder_lpg_products/'),
        ),
        migrations.AddField(
            model_name='cylinderlpgasproductsadd',
            name='product_price',
            field=models.CharField(default=datetime.datetime(2025, 8, 13, 10, 57, 21, 299496, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
