# Generated by Django 5.1.4 on 2025-08-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='delivery_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
